name: ci

on:
  push:
    branches:
      - main

jobs:
  dockerloginbuildpush:
    runs-on: ubuntu-latest
    steps:
      - name: login to Docker.io
        uses: docker/login-action@v1
        with:
          registry: docker.io
          username: ${{ docker.actor }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - uses: actions/checkout@v2
      - name: create image from repository
        run: docker build -t ${{ github.actor }}/<img-name> .
      - name: push image to Docker Container Registry
        run: docker push ${{ github.actor }}/<img-name>:latest
